version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '4001:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  php:
    container_name: php
    image: php:8-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 6001:80
    
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol:
networks:
  frontend:
  backend: